databases:
  # データベースサーバ
  - name: django_test_db_name
    region: singapore
    plan: free
    databaseName: django_test_db_name
    user: app_user

services:
  # Django
  - type: web
    name: django-test-app
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_website.wsgi:application"
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_test_db_name
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
    autoDeploy: true